### ISSUE TITLE
openstuder GW, Influxdb storage driver

### ISSUE THREAD

**Issue by Jusufs** [OpenStuder/openstuder-client-python#3]
Hi.
Please send me info about possibility to store datalogs into Influxdb database.
Are somewhere working on a Influxdb storage driver for openstuder gateway ?

**Comment by cm0x4D** [comment]
There are no plans for InfluxDB storage extension. 

However it should not be that hard to implement such an extension using Qt's `QNetworkAccessManager` class and the InfluxDB line protocol.
