### ISSUE TITLE
find_properties - function arguments values from virtual and functions_mask parameters

### ISSUE THREAD

**Issue by Jusufs** [OpenStuder/openstuder-client-python#4]
1. Please send me info about possible values for this two or probably ? more parameters:

Traceback
  File "/home/jozef/SYNC/find_prop.py", line 11, in <module>
    status, id_, count, properties = client.find_properties('xcom.xt1.3000', **virtual =** ???, **functions_mask =** ???)
ValueError: too many values to unpack (expected 4)

2. How to enumerate not only devicecount of studer devices, but also names e.g. xt1, vt2, bat etc. please ?
   Determination of component names in a Studer system, or standart address numbers of Studer devices according    communication protocol documentation.
Thanks.

**Comment by cm0x4D** [comment]
1. There is a bug in the Python client and the documentation is not up-to-date. I will change that now.
2. The enumerate() command actively detects devices on the bus and depending the version of the RCC it can take quite a while. This is only needed if the topology changes and is executed automatically at boot, so no need to call it yourself. If you are interested in the actual topology, use the describe() function.

**Comment by cm0x4D** [comment]
See 3add271c04cd076b00ce110c960ffc47314971a2 and 0c69b44e822c7dae50a7c64d72f1dddeb1a80b6c
